const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
exports.checkControls=async({call,js,click,delay,out,width,height})=>{
  const geometry=()=>js("(()=>{const r=document.getElementById('globe').getBoundingClientRect();return {height:r.height,width:r.width}})()");
  const before=await geometry();
  await click('#mobileControls');
  assert.equal(await js("document.getElementById('timelineSettings').hidden"),false);
  assert.deepEqual(await geometry(),before,'settings must not resize the globe');
  assert.ok(await js("(()=>{const r=document.getElementById('timelineSettings').getBoundingClientRect();return r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight})()"),'settings must fit the viewport');
  fs.writeFileSync(path.join(out,`settings-${width}-${height}.png`),Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await call('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  await call('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27});
  assert.equal(await js("document.getElementById('timelineSettings').hidden&&document.activeElement.id==='mobileControls'"),true);
  await click('#mobileControls');await click('#closeTimeline');
  assert.equal(await js("document.getElementById('mobileControls').getAttribute('aria-expanded')"),'false');
  await click('#mobileExplore');
  assert.deepEqual(await geometry(),before,'More must not resize the globe');
  await click('#sources');assert.equal(await js("document.getElementById('sourceDialog').open"),true);
  await click('#closeDialog');
};
exports.checkLenses=async({call,js,click,navigate,delay,until,base,out})=>{
  await call('Emulation.setDeviceMetricsOverride',{width:1210,height:702,deviceScaleFactor:1,mobile:false});
  await call('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});
  await navigate(base);
  const select=async(selector,index)=>{await js(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});e.selectedIndex=${index};e.dispatchEvent(new Event('change',{bubbles:true}));})()`);await delay(150);};
  await click('#mobileControls');
  await select('#metric',1);await select('#window',1);await select('#baseline',1);await select('#speed',2);
  assert.deepEqual(await js("({metric:state.metric,window:state.window,baseline:state.baseline,speed:document.getElementById('speed').value})"),{metric:1,window:1,baseline:'january',speed:'28'});
  await click('#closeTimeline');
  const start=await js('state.index');await click('#back');assert.equal(await js('state.index'),start-1);
  await click('#forward');assert.equal(await js('state.index'),start);
  await click('#play');await delay(650);assert.equal(await js('state.playing'),true);
  await click('#play');assert.equal(await js('state.playing'),false);
  await click('#latest');
  const zoom=await js('state.zoom');await click('#zoomin');assert.ok(await js('state.zoom')>zoom);await click('#reset');assert.equal(await js('state.zoom'),1);
  await click('#browseToggle');await call('Input.insertText',{text:'Jebel Ali'});await delay(300);await click('#locations button');
  assert.equal(await js('passageSnapshot().place'),'Jebel Ali');
  const latestAvailable=await js('dates.filter((_,i)=>Number.isFinite(series[state.selected]?.[i]?.[state.metric])).at(-1)');
  await click('#latest');assert.equal(await js('passageSnapshot().date'),latestAvailable);
  assert.ok(latestAvailable<=await js('manifest.Daily_Ports_Data_latest'));
  await click('#pin');assert.equal(await js('state.pins.length'),1);
  await click('#share');const shared=await js('location.hash');await navigate(base+shared);assert.equal(await js('state.pins.length'),1);
  await click('#clearPins');assert.equal(await js('state.pins.length'),0);
  await click('#depthPanel summary');await click('#loadHistory');await until(()=>js('!!historyCache[state.selected]'));
  await js("document.querySelector('.detail').scrollTop=500");await delay(100);
  assert.ok(await js("(()=>{const p=document.getElementById('placeName').getBoundingClientRect(),d=document.querySelector('.detail').getBoundingClientRect();return p.top>=d.top-1&&p.bottom<d.bottom})()"),'selected place stays visible while details scroll');
  fs.writeFileSync(path.join(out,'details-expanded.png'),Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
  await click('#connections');await until(()=>js("state.mode==='connections'&&!!network"));
  assert.equal(await js("getComputedStyle(document.querySelector('.time-controls')).display"),'none');
  await select('#direction',1);assert.equal(await js("document.getElementById('direction').value"),'in');assert.ok(await js('links.length')>0);
  await click('#exposure');await until(()=>js("state.mode==='exposure'&&countryRows.length>0"));
  await select('#trade',1);assert.equal(await js("document.getElementById('trade').value"),'daily_export_value_at_risk');
  assert.equal(await js("getComputedStyle(document.querySelector('.time-controls')).display"),'none');
  await click('#change');await until(()=>js("state.mode==='change'"));
  assert.notEqual(await js("getComputedStyle(document.querySelector('.time-controls')).display"),'none');
  await click('#analyzeView');assert.equal(await js('aw.open'),true);
  await click('#analysisSetup summary');await click('#analysisSetup summary');
  await select('#analysisDisplay',1);assert.equal(await js("document.getElementById('analysisDailyPanel').hidden"),false);
  await click('#exploreView');assert.equal(await js('aw.open'),false);
};
